### ISSUE TITLE
Team Convention

### ISSUE THREAD

**Issue by BeedleEiEi** [it-kmitl-2018/group7#4]
Group7 Team Convention

**Comment by champillon** [comment]
ถ้าเป็น issue อื่นๆ ต้องทำเป็น Pull Request (PR) มานะครับ ไม่ใช่แค่เปิด issue เฉยๆ แล้ว push เข้า Branch Master ครับ ไม่งั้นพี่ไม่เห็น code ที่แก้ไข พี่ให้คะแนนไม่ถูกครับ

**Comment by BeedleEiEi** [comment]
รับทราบครับ
